### ISSUE TITLE
Re-structure the project

### ISSUE THREAD

**Issue by ebegoli** [ebegoli/ErrorProne#1]
Have a structure that has data, src and test folders and a [standard python project structure](http://python-guide-pt-br.readthedocs.io/en/latest/writing/structure/) including [tox](https://tox.readthedocs.io/en/latest/).

**Comment by Bowiemb** [comment]
Per your request I have included data, src, and test folders as well as included the standard python project structure and tox files. 

Currently, most of those files are currently place holders. 

Let me know if this structure is satisfactory, and I will close this issue.
